### ISSUE TITLE
docs: Add .meta.yml to each tool page and tool directory.

### ISSUE THREAD

**Issue by cwhite911** [OSGeo/grass#5221]
Right now we need to add the authors of tools to the markdown header so that it appears as an html meta tag. Currently, we are adding these things as part of docs build, but this will start to get messy if we want to full utilize the material mkdocs plugins. The mkdocs solution is to add a `.meta.yml` file to each tool directory. 

We can auto-generate the `.meta.yml` file for each tool and make that a new part of the tool configuration. This will allow us to have more control over how all of the  material for mkdocs plugins work.

The new structure would look like this:

```
/raster
    .meta.yml # Default meta values for all raster tools
    /r.tool
        /testsuite
        .meta.yml  #  Tool specific metadata
        main.c or r.tool.py
        r.tool.md
        Makefile
```

For example, a mock `.meta.yml` could look like.

## Meta

```yml

name: i.sam2
title: i.sam2 - GRASS GIS 8.5.0dev Reference Manual
subtitle: Something here
author: Corey T. White & GRASS Development Team
description: Integrates SAMGeo model with text prompt for segmentation in GRASS GIS.
keywords: imagery, segmentation, object recognition, deep learning
icon: material/emoticon-happy 
status: new or deprecated
```

## Tags plugin

```yml
tags: [ imagery, segmentation, object recognition, deep learning ]
```
## Social plugin

You can set a custom card variant

```yml
social:
  cards_layout: default/variant
```

Or a background color and image

```yml
social:
  cards_layout_options:
    background_color: blue             # Change background color
    background_image: null             # Remove background image
````

## Search plugin

Boost specific tools in the search results.

```yml
search:
  boost: 2
```
or exclude certain pages

```yml
search:
  exclude: true
```
